### ISSUE TITLE
wrong vendor 

### ISSUE THREAD

**Issue by lorenzocostalunga** [PingmanTools/MacAddressVendorLookup#2]
The mac address 00-80-a3-xx-xx-xx returns: "(see also 0800A3)"
instead of: "Lantronix # (see also 0800A3)"

**Comment by mdc88** [comment]
To clarify further, this happens anytime the manuf file entry has a comment (#) in it after the organization information.  I believe it is something to do with the binaryReader.ReadString() call in ParseBinaryVendorData

**Comment by nesspete** [comment]
Thanks for the heads up. The file wireshark format changed and the long manufacturer name was moved from the comment to an additional entry in the line. The parser didn't handle that change. This has been fixed on latest.
